### ISSUE TITLE
Define function by using Ruby method

### ISSUE THREAD

**Issue by YuukiWada** [odakahirokazu/RubyROOT#8]
I tried to define a user function and an argument error was generated.
```
user_function.rb:6:in `fuser': wrong number of arguments (0 for 2) (ArgumentError)
	from user_function.rb:11:in `<main>'

 *** Break *** segmentation violation
```
Could you tell me how to use Ruby Method for TF1 function.

I attach my scripts below.
```
require "RubyROOT"
include Root
include RootApp
include Math

def fuser(x, par)
  par[0]*(Math::E)**(-(x[0]-par[1])**2/(2*par[2]**2))
end

f1=Root::TF1.new("f1", "gaus(0)", -10.0, 10.0)
f2=Root::TF1.new("f1", fuser, -10.0, 10.0, 3)
c1=Root::TCanvas.new("c1", "c1", 640, 480)
f1.SetParameter(0, 10.0)
f1.SetParameter(1, 0.0)
f1.SetParameter(2, 2.0)

f2.SetParameter(0, 9.0)
f2.SetParameter(1, 0.0)
f2.SetParameter(2, 2.0)

f1.Draw()
f2.Draw()
f2.SetLineColor(3)
c1.Update()
run_app()
```

**Comment by yuasatakayuki** [comment]
Hi @YuukiWada 

Try something like the following.

```ruby
require "RubyROOT"

user_func = lambda{|xs, parameters|
  x = xs[0]
  a = parameters[0]
  b = parameters[1]
  return a*x + b
}

NUM_PARAMETERS = 2
f = Root::TF1.create("func", user_func, -100.0, 100.0, NUM_PARAMETERS)

# Set parameters (a, b)
f.SetParameter(0, 3)
f.SetParameter(1, 2.5)
puts f.Eval(10)
```

This example displays `32.5` when executed.
